set(CTEST_PROJECT_NAME "vidtk_all")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

if (NOT VIDTK_EC_TESTS)
  set(CTEST_DROP_METHOD "http")
  set(CTEST_DROP_SITE "www.kitware.com")
  set(CTEST_DROP_LOCATION "/CDash/submit.php?project=VidTK")
  set(CTEST_DROP_SITE_CDASH TRUE)
else ()
  set(CTEST_DROP_METHOD "https")
  set(CTEST_DROP_SITE "ecdash.kitware.com")
  set(CTEST_DROP_LOCATION "/CDash/submit.php?project=vidtk-ec")
  set(CTEST_DROP_SITE_CDASH TRUE)
  set(CTEST_CURL_OPTIONS CURLOPT_SSL_VERIFYHOST_OFF;CURLOPT_SSL_VERIFYPEER_OFF)
endif ()
